services:
  excel2csv:
    image: ghcr.io/gik986/excel2csvconverter:latest
    container_name: excel2csv
    restart: unless-stopped
    environment:
      TZ: Europe/Sofia
    env_file: .env
    volumes:
      - /mnt/pricelist:/data/pricelist
      - /mnt/logs:/data/logs
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    security_opt:
      - no-new-privileges:true
