# Generated by CodiumAI
import datetime
import os
import unittest

from utils import get_input_root_folder


# Generated by CodiumAI
class TestGetInputRootFolder(unittest.TestCase):

    #  Tests that the function returns the value of INPUT_FOLDER variable.
    def test_returns_input_folder(self):
        # Arrange
        date_now = datetime.datetime.now().strftime("%d.%m.%Y")
        expected = os.path.join("./test_input", date_now)

        # Act
        result = get_input_root_folder()

        # Assert
        self.assertEqual(result, expected)
