# Generated by CodiumAI
import datetime
import os
import unittest

from converter import get_output_root_folder, get_input_root_folder


class TestGetOutputRootFolder(unittest.TestCase):

    #  Tests that the function returns the value of the global variable OUTPUT_FOLDER when it is not empty.
    def test_happy_path(self):
        # Arrange
        date_now = datetime.datetime.now().strftime("%d.%m.%Y")
        expected_output = os.path.join("./test_output", date_now)

        # Act
        actual_output = get_output_root_folder()

        # Assert
        self.assertEqual(actual_output, expected_output)


# Generated by CodiumAI
class TestGetInputRootFolder(unittest.TestCase):

    #  Tests that the function returns the value of INPUT_FOLDER variable.
    def test_returns_input_folder(self):
        # Arrange
        date_now = datetime.datetime.now().strftime("%d.%m.%Y")
        expected = os.path.join("./test_input", date_now)

        # Act
        result = get_input_root_folder()

        # Assert
        self.assertEqual(result, expected)
